#tests = \
#	echo \
#	mvin_mvout \
#	mvin_mvout_stride \
#	mvin_mvout_acc \
#	mvin_mvout_acc_stride \
#	matmul_os \
#	matmul_ws \
#	matmul \
#	raw_hazard \
#	aligned \
#	padded \
#	tiled_matmul_os \
#	tiled_matmul_ws \
#	tiled_matmul_cpu \
#	tiled_matmul_option \
#	template

tests := \
	echo \
 	padded \
 	tiled_matmul_ws \
	template
