#tests = \
# echo \
#	mvin_mvout \
#	mvin_mvout_stride \
#	mvin_mvout_acc \
#	mvin_mvout_acc_stride \
#	matmul_os \
#	matmul_ws \
#	matmul \
#	raw_hazard \
#	aligned \
#	template

tests := \
	echo \
	template \

