#tests = \
#	identity \
#	identity_negative \
#	double \
#	double_keep_weights \
#	double_keep_weights_then_change \
#	random_matmuls \
#	large_matmul \
#	large_matmul_without_cpu \
#	very_large_matmul \
#	cifar_quant

tests = \
	large_matmul \
	large_matmul_without_cpu \
	very_large_matmul \
 	cifar_quant \
	gemm
